### ISSUE TITLE
exception

### ISSUE THREAD

**Issue by pkhadka56** [lusis/sensu_influxdb_handler#11]
/etc/sensu/extensions/influx.rb:18:in `post_init': undefined method`[]' for nil:NilClass (NoMethodError)
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-extension-1.1.2/lib/sensu/extension.rb:21:in `block in initialize'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:959:in`call'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:959:in `block in run_deferred_callbacks'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:956:in`times'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:956:in `run_deferred_callbacks'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in`run_machine'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.20.3/lib/sensu/server/process.rb:23:in`run'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.20.3/bin/sensu-server:10:in `<top (required)>'
        from /opt/sensu/bin/sensu-server:23:in`load'
        from /opt/sensu/bin/sensu-server:23:in `<main>'

**Comment by tgagor** [comment]
Looks like I have the same or similar:
```
"NoMethodError: undefined method `[]' for nil:NilClass
  /etc/sensu/extensions/influxdb.rb:42:in `run'
  /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-extension-1.5.0/lib/sensu/extension.rb:113:in `safe_run'
  /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.5/lib/sensu/server/handle.rb:120:in `handler_extension'
  /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.5/lib/sensu/server/handle.rb:146:in `handler_type_router'
  /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.5/lib/sensu/server/handle.rb:163:in `handle_event'
  /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.5/lib/sensu/server/process.rb:255:in `block (3 levels) in process_event'
  /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.5/lib/sensu/server/mutate.rb:19:in `block in mutator_callback'
  /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-extension-1.5.0/lib/sensu/extension.rb:114:in `block in safe_run'
  /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-extensions-json-1.0.0/lib/sensu/extensions/json.rb:16:in `run'
  /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-extension-1.5.0/lib/sensu/extension.rb:113:in `safe_run'
  /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.5/lib/sensu/server/mutate.rb:59:in `mutator_extension'
  /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.5/lib/sensu/server/mutate.rb:82:in `mutate_event'
  /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.5/lib/sensu/server/process.rb:254:in `block (2 levels) in process_event'
  /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.5/lib/sensu/server/filter.rb:303:in `block in filter_event'
  /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.5/lib/sensu/server/filter.rb:270:in `event_filtered?'
  /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.5/lib/sensu/server/filter.rb:301:in `filter_event'
  /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.5/lib/sensu/server/process.rb:253:in `block in process_event'
  /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.5/lib/sensu/server/process.rb:251:in `each'
  /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.5/lib/sensu/server/process.rb:251:in `process_event'
  /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.5/lib/sensu/server/process.rb:663:in `block (4 levels) in process_check_result'
  /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.5/lib/sensu/server/process.rb:500:in `update_event_registry'
  /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.5/lib/sensu/server/process.rb:662:in `block (3 levels) in process_check_result'
  /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.5/lib/sensu/server/process.rb:560:in `block (3 levels) in create_event'
  /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.5/lib/sensu/server/process.rb:468:in `event_silenced?'
  /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.5/lib/sensu/server/process.rb:559:in `block (2 levels) in create_event'
  /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-redis-1.6.0/lib/sensu/redis/client.rb:315:in `dispatch_response'
  /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-redis-1.6.0/lib/sensu/redis/client.rb:335:in `parse_response_line'
  /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-redis-1.6.0/lib/sensu/redis/client.rb:365:in `receive_data'
  /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run_machine'
  /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run'
  /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.5/lib/sensu/server/process.rb:31:in `run'
  /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.5/exe/sensu-server:10:in `<top (required)>'
  /opt/sensu/bin/sensu-server:22:in `load'
  /opt/sensu/bin/sensu-server:22:in `<main>'"
```
