### ISSUE TITLE
"cannot load such file -- influxdb"

### ISSUE THREAD

**Issue by ghost** [lusis/sensu_influxdb_handler#3]
I have done a "gem install influxdb", and i setup my /etc/sensu/handlers/metrics.json to look like the example. Is there something else I'm missing in this error or in the requirements?

From sensu-server log:

{"timestamp":"2014-06-24T08:30:31.857970-0700","level":"error","message":"failed to require extension","extension_file":"/etc/sensu/extensions/influx.rb","error":{"path":"influxdb","~mesg":"cannot load such file -- influxdb","~bt":["/opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:53:in `require'","/opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:53:in`require'","/etc/sensu/extensions/influx.rb:4:in `<top (required)>'","/opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:53:in`require'","/opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:53:in `require'","/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.12.6/lib/sensu/extensions.rb:31:in`block in require_directory'","/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.12.6/lib/sensu/extensions.rb:29:in `each'","/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.12.6/lib/sensu/extensions.rb:29:in`require_directory'","/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.12.6/lib/sensu/base.rb:59:in `extensions'","/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.12.6/lib/sensu/server.rb:24:in`initialize'","/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.12.6/lib/sensu/server.rb:13:in `new'","/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.12.6/lib/sensu/server.rb:13:in`run'","/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.12.6/bin/sensu-server:10:in `<top (required)>'","/opt/sensu/bin/sensu-server:23:in`load'","/opt/sensu/bin/sensu-server:23:in `<main>'"]}}
{"timestamp":"2014-06-24T08:30:31.863903-0700","level":"warn","message":"ignoring extension","extension_file":"/etc/sensu/extensions/influx.rb"}

**Comment by nohtyp** [comment]
He answers this same question in my closed question...

https://github.com/lusis/sensu_influxdb_handler/issues/2
